/**
 * DepEd's Kindergarten competencies, from `api/database/data/matatag/kindergarten.v1.json`,
 * for the Settings preview only. A real card always prints the catalog the server sends.
 */
export const SAMPLE_KINDER_AREAS: Array<{ title: string; rows: Array<[domain: string | null, label: string, text: string]> }> = [
  {
    title: 'I. Sensory Perceptual and Motor Development',
    rows: [
      [null, '1', 'Identifies external body parts and their functions'],
      [null, '2', 'Identifies ways to care for and protects one’s body'],
      [null, '3', 'Demonstrates gross motor skills (locomotor, non-locomotor)'],
      [null, '4', 'Moves body parts as directed'],
      [null, '5', 'Demonstrates fine motor skills (tearing, cutting, rolling, molding with playdough)'],
    ],
  },
  {
    title: 'II. Socio-emotional Development',
    rows: [
      [null, '1', 'Identifies and expresses feelings in appropriate ways'],
      [null, '2', 'Recognizes and respect feelings of others'],
      [null, '3', 'Expresses needs and preferences'],
      [null, '4', 'Behaves appropriately in different situations'],
      [null, '5', 'Participates in classroom routines and activities'],
      [null, '6', 'Follows classroom and school rules'],
      [null, '7', 'Fulfills classroom responsibilities'],
    ],
  },
  {
    title: 'III. Cognitive Development',
    rows: [
      [null, '1', 'Identifies attributes of objects (color, shape, size)'],
      [null, '2', 'Matches objects based on attributes'],
      [null, '3', 'Describes objects based on attributes (shape, color, taste, texture)'],
      [null, '4', 'Classifies objects by a single attribute (color, shape, size)'],
      [null, '5', 'Reclassifies objects according to multiple attributes'],
      [null, '6', 'Arranges objects according to specific attributes'],
      [null, '7', 'Recognizes, extends and create patterns using concrete objects'],
      [null, '8', 'Measures size, length, capacity and mass of objects using non-standard measuring tools'],
      [null, '9', 'Identifies position of objects (in, on, over, under, top, bottom)'],
      [null, '10', 'Compares quantities of objects (more/less)'],
      [null, '11', 'Counts with one-to-one correspondence'],
      [null, '12', 'Recognizes numerals'],
      [null, '13', 'Matches numerals to objects'],
      [null, '14', 'Adds and subtracts using concrete objects'],
      [null, '15', 'Recognizes clock as measure of time (hours and minutes)'],
      [null, '16', 'Shows awareness and care for the natural and physical environment'],
      [null, '17', 'Talks about participation in cultural and religious activities'],
      [null, '18', 'Shows awareness of the importance of caring for the natural and physical environment through simple practices (e.g., sorting trash, helping to clean up)'],
      [null, '19', 'Predicts outcomes in familiar stories read aloud in class'],
      [null, '20', 'Suggests solutions to problems in class activities and stories read aloud in class'],
    ],
  },
  {
    title: 'IV. Language, Literacy, and Communication Development',
    rows: [
      ['A. Listening and Viewing', '1', 'Identifies familiar environmental sound'],
      ['A. Listening and Viewing', '2', 'Recalls what happens first, middle and end in a story'],
      ['A. Listening and Viewing', '3', 'Retells story in sequence'],
      ['A. Listening and Viewing', '4', 'Follows 1-2 step instructions'],
      ['B. Sight Word Recognition', '5', 'Recognizes non-decodable words in and out of context automatically'],
      ['B. Sight Word Recognition', '6', 'Recognizes sight words'],
      ['C. Speaking', '7', 'Identifies first and last name'],
      ['C. Speaking', '8', 'Identifies classmates, teachers, family member'],
      ['C. Speaking', '9', 'Identifies familiar objects at home, in school and in the community'],
      ['C. Speaking', '10', 'Uses polite greetings and courteous expressions in varied situations'],
      ['C. Speaking', '11', 'Retells personal experiences to story events'],
      ['C. Speaking', '12', 'Expresses ideas and feelings using phrases and simple sentences'],
      ['D. Reading — Phonological/Phonemic Awareness', '13', 'Orally segment sounds: a. syllable; b. onset and rime; c. phoneme by phoneme'],
      ['D. Reading — Letter Knowledge', '14', 'Identifies uppercase letters'],
      ['D. Reading — Letter Knowledge', '15', 'Identifies lowercase letters'],
      ['D. Reading — Letter Knowledge', '16', 'Matches upper and lowercase letters'],
      ['D. Reading — Letter Sound Relationship', '17', 'Identifies letter sounds'],
      ['D. Reading — Letter Sound Relationship', '18', 'Matches letters and their corresponding sounds'],
      ['E. Comprehension', '19', 'Uses a variety of strategies to gain meaning of leveled texts'],
      ['E. Comprehension', '20', 'Uses print and illustrations to make meaning'],
      ['F. Concepts of Print', '21', 'Demonstrates book handling skills'],
      ['F. Concepts of Print', '22', 'Distinguishes between letters, words, and sentences'],
      ['F. Concepts of Print', '23', 'Demonstrates awareness of print (left to right and top to bottom)'],
      ['G. Writing', '24', 'Traces/draws/copies shapes, designs, pictures'],
      ['G. Writing', '25', 'Traces/copies/writes name, words'],
      ['G. Writing', '26', 'Writes uppercase and lowercase letters'],
      ['G. Writing', '27', 'Spells sight words'],
      ['G. Writing', '28', 'Spells simple words phonetically'],
    ],
  },
]
