version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: scholasticcloud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: scholasticcloud
      POSTGRES_USER: scholasticcloud
      POSTGRES_PASSWORD: scholasticcloud123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - scholasticcloud-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scholasticcloud -d scholasticcloud"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  scholasticcloud-network:
    driver: bridge 