version: '3.8'

services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.11
    container_name: schoolmate_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: schoolmate
      MYSQL_USER: schoolmate_user
      MYSQL_PASSWORD: schoolmate_password
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./api/database/init:/docker-entrypoint-initdb.d
    networks:
      - schoolmate_network

  # Laravel API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: schoolmate_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      DB_CONNECTION: mariadb
      DB_HOST: srv1417.hstgr.io
      DB_PORT: 3306
      DB_DATABASE: u825103209_scholastic_v2
      DB_USERNAME: u825103209_scholastic_v2
      DB_PASSWORD: K2CTmp^*z
    depends_on:
      - mariadb
    networks:
      - schoolmate_network
    command: >
      sh -c "
        php artisan key:generate &&
        php artisan migrate:fresh --seed &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  # React App with Vite
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: schoolmate_app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000/api
      NODE_ENV: development
    depends_on:
      - api
    networks:
      - schoolmate_network
    command: npm run dev -- --host 0.0.0.0

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: schoolmate_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: schoolmate_user
      PMA_PASSWORD: schoolmate_password
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mariadb
    networks:
      - schoolmate_network

volumes:
  mariadb_data:

networks:
  schoolmate_network:
    driver: bridge
