name: Deploy APP to Production

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Step 3: Create .env file from secret (before building)
      - name: Create .env file
        run: |
          cd app
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

      # Step 4: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          cd app
          npm ci
          npm run build  # This builds your Vite project into the 'dist' folder

      # Step 5: Deploy the dist folder to Hostinger using FTP
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.scholastic.cloud
          username: u825103209.scholastic.cloud
          password: 127.0.0.1ismyhomE
          local-dir: app/dist/
          server-dir: /public_html/v2/app/
